services:
#  elasticsearch:
#    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10'
#    environment:
#      - 'ELASTIC_PASSWORD=secret'
#      - 'discovery.type=single-node'
#      - 'xpack.security.enabled=false'
#    ports:
#      - '3200'
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=nullcom
      - POSTGRES_PASSWORD=nullcom123$
      - POSTGRES_USER=root
    ports:
      - '5432:5432'
    container_name: postgres
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - RABBITMQ_DEFAULT_PASS=nullcom123$
      - RABBITMQ_DEFAULT_USER=nullcom
    ports:
      - '5672:5672'
    container_name: rabbitMQ
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    container_name: redis
